[build]
builder = "nixpacks"
buildCommand = "npm install"

[deploy]
startCommand = "node index.js"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[deploy.env]
NODE_ENV = "production"

[[services]]
name = "wa-bot"
type = "web"
domain = "wa-bot.up.railway.app"

[[volumes]]
name = "auth-storage"
mountPath = "/data" 