const questions = [
  {
    question: "Sebutkan makanan yang biasa dijual di pinggir jalan!",
    answers: [
      { text: "nasi goreng", points: 35 },
      { text: "mie goreng", points: 25 },
      { text: "sate", points: 20 },
      { text: "bakso", points: 15 },
      { text: "martabak", points: 10 },
      { text: "gorengan", points: 5 },
    ],
  },
  {
    question: "Sebutkan benda yang ada di dalam tas sekolah!",
    answers: [
      { text: "buku", points: 30 },
      { text: "pulpen", points: 25 },
      { text: "pensil", points: 20 },
      { text: "penghapus", points: 15 },
      { text: "penggaris", points: 10 },
      { text: "dompet", points: 5 },
    ],
  },
  {
    question: "Sebutkan hewan yang bisa terbang!",
    answers: [
      { text: "burung", points: 35 },
      { text: "nyamuk", points: 25 },
      { text: "lalat", points: 20 },
      { text: "kupu-kupu", points: 15 },
      { text: "lebah", points: 10 },
      { text: "kelelawar", points: 5 },
      { text: "capung", points: 5 },
    ],
  },
  {
    question: "Sebutkan benda yang ada di dapur!",
    answers: [
      { text: "kompor", points: 30 },
      { text: "panci", points: 25 },
      { text: "wajan", points: 20 },
      { text: "sendok", points: 15 },
      { text: "garpu", points: 10 },
      { text: "pisau", points: 10 },
      { text: "piring", points: 5 },
      { text: "gelas", points: 5 },
    ],
  },
  {
    question: "Sebutkan olahraga yang menggunakan bola!",
    answers: [
      { text: "sepak bola", points: 35 },
      { text: "basket", points: 30 },
      { text: "voli", points: 25 },
      { text: "tenis", points: 15 },
      { text: "badminton", points: 10 },
      { text: "golf", points: 5 },
      { text: "rugby", points: 5 },
    ],
  },
  {
    question: "Sebutkan benda yang ada di kamar mandi!",
    answers: [
      { text: "sabun", points: 30 },
      { text: "shampo", points: 25 },
      { text: "handuk", points: 20 },
      { text: "sikat gigi", points: 15 },
      { text: "pasta gigi", points: 10 },
      { text: "gayung", points: 5 },
      { text: "ember", points: 5 },
    ],
  },
  {
    question: "Sebutkan benda yang ada di ruang tamu!",
    answers: [
      { text: "sofa", points: 30 },
      { text: "meja", points: 25 },
      { text: "kursi", points: 20 },
      { text: "tv", points: 15 },
      { text: "lukisan", points: 10 },
      { text: "vas bunga", points: 5 },
      { text: "karpet", points: 5 },
    ],
  },
  {
    question: "Sebutkan benda yang ada di kamar tidur!",
    answers: [
      { text: "kasur", points: 30 },
      { text: "bantal", points: 25 },
      { text: "selimut", points: 20 },
      { text: "lemari", points: 15 },
      { text: "meja belajar", points: 10 },
      { text: "lampu", points: 5 },
      { text: "jam dinding", points: 5 },
    ],
  },
  {
    question: "Sebutkan hal yang biasa ada di dalam tas perempuan!",
    answers: [
      { text: "dompet", points: 30 },
      { text: "hp", points: 25 },
      { text: "makeup", points: 20 },
      { text: "tisu", points: 10 },
      { text: "sisir", points: 5 },
      { text: "powerbank", points: 5 },
      { text: "parfum", points: 5 },
    ],
  },
  {
    question: "Sebutkan tempat yang sering dijadikan lokasi kencan pertama!",
    answers: [
      { text: "cafe", points: 35 },
      { text: "bioskop", points: 30 },
      { text: "mall", points: 20 },
      { text: "taman", points: 10 },
      { text: "restoran", points: 5 },
      { text: "pantai", points: 5 },
    ],
  },
  {
    question: "Sebutkan kegiatan yang biasa dilakukan saat weekend!",
    answers: [
      { text: "jalan-jalan", points: 30 },
      { text: "nonton film", points: 25 },
      { text: "tidur", points: 20 },
      { text: "olahraga", points: 15 },
      { text: "belanja", points: 10 },
    ],
  },
  {
    question: "Sebutkan alasan orang pergi ke gym!",
    answers: [
      { text: "menurunkan berat badan", points: 35 },
      { text: "membentuk otot", points: 30 },
      { text: "kesehatan", points: 20 },
      { text: "mengisi waktu luang", points: 10 },
      { text: "ikut teman", points: 5 },
    ],
  },
  {
    question: "Sebutkan alat yang digunakan untuk berkebun!",
    answers: [
      { text: "cangkul", points: 30 },
      { text: "sekop", points: 25 },
      { text: "gunting tanaman", points: 20 },
      { text: "selang", points: 15 },
      { text: "pot", points: 10 },
    ],
  },
  {
    question: "Sebutkan hewan yang biasa dipelihara di rumah!",
    answers: [
      { text: "kucing", points: 40 },
      { text: "anjing", points: 30 },
      { text: "ikan", points: 15 },
      { text: "burung", points: 10 },
      { text: "kelinci", points: 5 },
    ],
  },
  {
    question: "Sebutkan sesuatu yang sering dicari saat listrik mati!",
    answers: [
      { text: "lilin", points: 35 },
      { text: "senter", points: 30 },
      { text: "power bank", points: 15 },
      { text: "korek api", points: 10 },
      { text: "lampu darurat", points: 10 },
    ],
  },
  {
    question: "Sebutkan benda yang sering ada di meja kerja!",
    answers: [
      { text: "laptop", points: 40 },
      { text: "buku catatan", points: 20 },
      { text: "pena", points: 15 },
      { text: "stapler", points: 10 },
      { text: "mouse", points: 10 },
      { text: "cangkir kopi", points: 5 },
    ],
  },
  {
    question: "Sebutkan buah yang sering dijadikan jus!",
    answers: [
      { text: "jeruk", points: 30 },
      { text: "mangga", points: 25 },
      { text: "alpukat", points: 20 },
      { text: "melon", points: 10 },
      { text: "pisang", points: 10 },
      { text: "stroberi", points: 5 },
    ],
  },
  {
    question: "Sebutkan sesuatu yang sering dilakukan sebelum tidur!",
    answers: [
      { text: "gosok gigi", points: 35 },
      { text: "cuci muka", points: 25 },
      { text: "berdoa", points: 20 },
      { text: "cek ponsel", points: 15 },
      { text: "minum air", points: 5 },
    ],
  },
  {
    question: "Sebutkan alasan orang bangun kesiangan!",
    answers: [
      { text: "tidur terlalu malam", points: 40 },
      { text: "alarm tidak berbunyi", points: 25 },
      { text: "mati lampu", points: 15 },
      { text: "kelelahan", points: 10 },
      { text: "tidak ada yang membangunkan", points: 10 },
    ],
  },
  {
    question: "Sebutkan sesuatu yang biasanya ada di dalam kulkas!",
    answers: [
      { text: "telur", points: 30 },
      { text: "susu", points: 25 },
      { text: "sayur", points: 20 },
      { text: "buah", points: 15 },
      { text: "air dingin", points: 10 },
    ],
  },
  {
    question: "Sebutkan alat elektronik yang ada di dapur!",
    answers: [
      { text: "rice cooker", points: 35 },
      { text: "blender", points: 30 },
      { text: "kulkas", points: 20 },
      { text: "oven", points: 10 },
      { text: "microwave", points: 5 },
    ],
  },
  {
    question: "Sebutkan tempat yang sering macet!",
    answers: [
      { text: "jalan raya", points: 40 },
      { text: "pasar", points: 30 },
      { text: "perempatan lampu merah", points: 15 },
      { text: "jalan tol", points: 10 },
      { text: "depan sekolah", points: 5 },
    ],
  },
  {
    question:
      "Sebutkan sesuatu yang sering ditanyakan oleh kasir di minimarket!",
    answers: [
      { text: "pakai kartu member?", points: 40 },
      { text: "mau sekalian isi pulsa?", points: 30 },
      { text: "butuh kantong plastik?", points: 15 },
      { text: "ada uang pas?", points: 10 },
      { text: "mau bayar pakai apa?", points: 5 },
    ],
  },
  {
    question: "Sebutkan sesuatu yang sering dicari saat menonton film!",
    answers: [
      { text: "popcorn", points: 35 },
      { text: "minuman", points: 30 },
      { text: "remote", points: 15 },
      { text: "selimut", points: 10 },
      { text: "bantal", points: 10 },
    ],
  },
  {
    question: "Sebutkan sesuatu yang sering dicari saat ingin keluar rumah!",
    answers: [
      { text: "kunci", points: 40 },
      { text: "dompet", points: 30 },
      { text: "ponsel", points: 20 },
      { text: "sepatu", points: 5 },
      { text: "jaket", points: 5 },
    ],
  },
  {
    question: "Sebutkan sesuatu yang bisa pecah!",
    answers: [
      { text: "gelas", points: 40 },
      { text: "piring", points: 30 },
      { text: "telur", points: 15 },
      { text: "lampu", points: 10 },
      { text: "cermin", points: 5 },
    ],
  },
  {
    question: "Apa yang biasa dilakukan orang saat listrik mati?",
    answers: [
      { text: "tidur", points: 30 },
      { text: "main HP", points: 25 },
      { text: "ngobrol", points: 20 },
      { text: "main kartu", points: 15 },
      { text: "nyalain lilin", points: 10 },
    ],
  },
  {
    question: "Sebutkan tempat favorit nyamuk hinggap di tubuh!",
    answers: [
      { text: "kaki", points: 35 },
      { text: "tangan", points: 30 },
      { text: "leher", points: 20 },
      { text: "telinga", points: 10 },
      { text: "punggung", points: 5 },
    ],
  },
  {
    question: "Apa yang sering dilakukan orang di depan cermin?",
    answers: [
      { text: "selfie", points: 35 },
      { text: "dandan", points: 30 },
      { text: "ngomong sendiri", points: 20 },
      { text: "nyanyi", points: 10 },
      { text: "joget", points: 5 },
    ],
  },
  {
    question: "Sebutkan alasan klasik saat putus cinta!",
    answers: [
      { text: "tidak cocok", points: 35 },
      { text: "ada orang ketiga", points: 30 },
      { text: "LDR", points: 20 },
      { text: "beda prinsip", points: 10 },
      { text: "fokus karir", points: 5 },
    ],
  },
  {
    question: "Sebutkan sesuatu yang sering bikin orang bangun tengah malam!",
    answers: [
      { text: "kebelet pipis", points: 40 },
      { text: "mimpi buruk", points: 25 },
      { text: "nyamuk", points: 20 },
      { text: "suara aneh", points: 10 },
      { text: "haus", points: 5 },
    ],
  },
  {
    question: "Sebutkan sesuatu yang sering bikin panik!",
    answers: [
      { text: "HP hilang", points: 40 },
      { text: "dompet ketinggalan", points: 30 },
      { text: "kendaraan mogok", points: 15 },
      { text: "baterai habis", points: 10 },
    ],
  },
  {
    question: "Sebutkan sesuatu yang sering dipencet!",
    answers: [
      { text: "remote TV", points: 30 },
      { text: "tombol HP", points: 25 },
      { text: "lift", points: 20 },
      { text: "klakson", points: 15 },
      { text: "jerawat", points: 10 },
    ],
  },
  {
    question: "Sebutkan nama negara yang berada di Asia Tenggara!",
    answers: [
      { text: "Indonesia", points: 30 },
      { text: "Malaysia", points: 25 },
      { text: "Thailand", points: 20 },
      { text: "Singapura", points: 15 },
      { text: "Vietnam", points: 10 },
      { text: "Filipina", points: 5 },
      { text: "Brunei Darussalam", points: 5 },
      { text: "Laos", points: 5 },
      { text: "Myanmar", points: 5 },
      { text: "Kamboja", points: 5 },
      { text: "Timor-Leste", points: 5 },
    ],
  },
  {
    question: "Sebutkan nama klub sepak bola terkenal di dunia!",
    answers: [
      { text: "Barcelona", points: 30 },
      { text: "Real Madrid", points: 25 },
      { text: "Manchester United", points: 20 },
      { text: "Liverpool", points: 10 },
      { text: "Bayern Munchen", points: 10 },
      { text: "PSG", points: 5 },
    ],
  },
  {
    question: "Sebutkan jenis hewan yang hidup di laut!",
    answers: [
      { text: "ikan", points: 30 },
      { text: "hiu", points: 25 },
      { text: "ubur-ubur", points: 15 },
      { text: "paus", points: 15 },
      { text: "lumba-lumba", points: 10 },
      { text: "gurita", points: 5 },
    ],
  },
  {
    question: "Sebutkan planet yang ada di tata surya!",
    answers: [
      { text: "Bumi", points: 25 },
      { text: "Mars", points: 20 },
      { text: "Jupiter", points: 20 },
      { text: "Venus", points: 15 },
      { text: "Saturnus", points: 10 },
      { text: "Merkurius", points: 10 },
      { text: "Uranus", points: 10 },
      { text: "Neptunus", points: 5 },
    ],
  },
  {
    question: "Sebutkan nama superhero dari film Marvel!",
    answers: [
      { text: "Spider-Man", points: 30 },
      { text: "Iron Man", points: 25 },
      { text: "Captain America", points: 20 },
      { text: "Thor", points: 15 },
      { text: "Hulk", points: 5 },
      { text: "Black Panther", points: 5 },
    ],
  },
  {
    question: "Sebutkan nama gunung terkenal di Indonesia!",
    answers: [
      { text: "Gunung Rinjani", points: 30 },
      { text: "Gunung Semeru", points: 25 },
      { text: "Gunung Merapi", points: 20 },
      { text: "Gunung Bromo", points: 15 },
      { text: "Gunung Kerinci", points: 5 },
      { text: "Gunung Slamet", points: 5 },
    ],
  },
  {
    question: "Sebutkan bahasa pemrograman yang populer!",
    answers: [
      { text: "Python", points: 30 },
      { text: "JavaScript", points: 25 },
      { text: "Java", points: 20 },
      { text: "C++", points: 10 },
      { text: "PHP", points: 10 },
      { text: "Go", points: 5 },
    ],
  },
  {
    question: "Sebutkan warna primer dalam seni rupa!",
    answers: [
      { text: "merah", points: 35 },
      { text: "kuning", points: 35 },
      { text: "biru", points: 30 },
    ],
  },
  {
    question: "Sebutkan jenis burung yang bisa menirukan suara manusia!",
    answers: [
      { text: "burung beo", points: 40 },
      { text: "burung kakatua", points: 30 },
      { text: "burung nuri", points: 20 },
      { text: "burung jalak", points: 10 },
    ],
  },
  {
    question: "Sebutkan klub sepak bola asal Inggris!",
    answers: [
      { text: "Manchester United", points: 30 },
      { text: "Liverpool", points: 25 },
      { text: "Chelsea", points: 20 },
      { text: "Arsenal", points: 15 },
      { text: "Manchester City", points: 10 },
    ],
  },
  {
    question: "Sebutkan hewan yang berkembang biak dengan bertelur!",
    answers: [
      { text: "ayam", points: 30 },
      { text: "ikan", points: 25 },
      { text: "burung", points: 20 },
      { text: "penyu", points: 15 },
      { text: "katak", points: 10 },
    ],
  },
  {
    question: "Sebutkan negara yang pernah menjadi juara Piala Dunia!",
    answers: [
      { text: "Brasil", points: 30 },
      { text: "Jerman", points: 25 },
      { text: "Italia", points: 20 },
      { text: "Argentina", points: 15 },
      { text: "Prancis", points: 10 },
    ],
  },
  {
    question: "Sebutkan benda yang dapat mengapung di air!",
    answers: [
      { text: "kayu", points: 30 },
      { text: "plastik", points: 25 },
      { text: "styrofoam", points: 20 },
      { text: "bola", points: 15 },
      { text: "perahu", points: 10 },
    ],
  },
  {
    question: "Sebutkan contoh hewan herbivora!",
    answers: [
      { text: "sapi", points: 30 },
      { text: "kambing", points: 25 },
      { text: "gajah", points: 20 },
      { text: "kuda", points: 15 },
      { text: "rusa", points: 10 },
    ],
  },
  {
    question: "Sebutkan negara yang berada di benua Eropa!",
    answers: [
      { text: "Jerman", points: 30 },
      { text: "Prancis", points: 25 },
      { text: "Italia", points: 20 },
      { text: "Belanda", points: 15 },
      { text: "Spanyol", points: 10 },
    ],
  },
  {
    question: "Sebutkan bagian tubuh manusia yang jumlahnya dua!",
    answers: [
      { text: "mata", points: 30 },
      { text: "telinga", points: 25 },
      { text: "tangan", points: 20 },
      { text: "kaki", points: 15 },
      { text: "paru-paru", points: 10 },
    ],
  },
  {
    question: "Sebutkan nama benua di dunia!",
    answers: [
      { text: "Asia", points: 30 },
      { text: "Eropa", points: 25 },
      { text: "Afrika", points: 20 },
      { text: "Amerika", points: 15 },
      { text: "Australia", points: 10 },
    ],
  },
  {
    question: "Sebutkan nama-nama tokoh dalam dunia sepak bola!",
    answers: [
      { text: "Lionel Messi", points: 30 },
      { text: "Cristiano Ronaldo", points: 25 },
      { text: "Neymar", points: 20 },
      { text: "Kylian Mbappé", points: 15 },
      { text: "Erling Haaland", points: 10 },
    ],
  },
  {
    question: "Sebutkan nama logam yang sering digunakan!",
    answers: [
      { text: "besi", points: 30 },
      { text: "tembaga", points: 25 },
      { text: "aluminium", points: 20 },
      { text: "emas", points: 15 },
      { text: "perak", points: 10 },
    ],
  },
  {
    question: "Sebutkan jenis olahraga selain sepak bola!",
    answers: [
      { text: "basket", points: 30 },
      { text: "voli", points: 25 },
      { text: "renang", points: 20 },
      { text: "bulu tangkis", points: 15 },
      { text: "tenis", points: 10 },
    ],
  },
  {
    question: "Sebutkan jenis batuan alam!",
    answers: [
      { text: "granite", points: 30 },
      { text: "marmer", points: 25 },
      { text: "batu bara", points: 20 },
      { text: "batu kapur", points: 15 },
      { text: "batu pasir", points: 10 },
    ],
  },
  {
    question: "Sebutkan bahasa pemrograman untuk website!",
    answers: [
      { text: "HTML", points: 25 },
      { text: "CSS", points: 25 },
      { text: "JavaScript", points: 25 },
      { text: "PHP", points: 15 },
      { text: "Python", points: 10 },
    ],
  },
  {
    question: "Sebutkan unsur penting dalam tabel periodik!",
    answers: [
      { text: "hidrogen", points: 30 },
      { text: "oksigen", points: 25 },
      { text: "karbon", points: 20 },
      { text: "nitrogen", points: 15 },
      { text: "helium", points: 10 },
    ],
  },
  {
    question: "Sebutkan jenis planet gas raksasa di tata surya!",
    answers: [
      { text: "Jupiter", points: 30 },
      { text: "Saturnus", points: 25 },
      { text: "Uranus", points: 20 },
      { text: "Neptunus", points: 15 },
    ],
  },
  {
    question: "Sebutkan nama-nama pulau besar di Indonesia!",
    answers: [
      { text: "Sumatera", points: 30 },
      { text: "Jawa", points: 25 },
      { text: "Kalimantan", points: 20 },
      { text: "Sulawesi", points: 15 },
      { text: "Papua", points: 10 },
    ],
  },
  {
    question: "Sebutkan aplikasi buatan Google!",
    answers: [
      { text: "Gmail", points: 30 },
      { text: "YouTube", points: 25 },
      { text: "Google Maps", points: 20 },
      { text: "Google Drive", points: 15 },
      { text: "Google Docs", points: 10 },
    ],
  },
  {
    question: "Sebutkan alat-alat yang menggunakan listrik!",
    answers: [
      { text: "setrika", points: 25 },
      { text: "kulkas", points: 25 },
      { text: "kipas angin", points: 20 },
      { text: "TV", points: 15 },
      { text: "mesin cuci", points: 15 },
    ],
  },
  {
    question: "Sebutkan warna pelangi!",
    answers: [
      { text: "merah", points: 15 },
      { text: "jingga", points: 15 },
      { text: "kuning", points: 15 },
      { text: "hijau", points: 15 },
      { text: "biru", points: 15 },
      { text: "nila", points: 15 },
      { text: "ungu", points: 10 },
    ],
  },
  {
    question: "Sebutkan negara yang terkenal dengan teknologi canggihnya!",
    answers: [
      { text: "Jepang", points: 30 },
      { text: "Korea Selatan", points: 25 },
      { text: "Amerika Serikat", points: 20 },
      { text: "Jerman", points: 15 },
      { text: "Cina", points: 10 },
    ],
  },
  {
    question: "Sebutkan klub sepak bola terkenal di dunia!",
    answers: [
      { text: "Real Madrid", points: 30 },
      { text: "Barcelona", points: 25 },
      { text: "Manchester United", points: 20 },
      { text: "Bayern Munchen", points: 15 },
      { text: "AC Milan", points: 10 },
    ],
  },
  {
    question: "Apa nama hewan tercepat di darat?",
    answers: [
      { text: "Cheetah", points: 30 },
      { text: "Kuda", points: 25 },
      { text: "Singa", points: 20 },
      { text: "Rusa", points: 15 },
    ],
  },
  {
    question: "Sebutkan nama-nama pahlawan nasional Indonesia!",
    answers: [
      { text: "Cut Nyak Dien", points: 30 },
      { text: "Pattimura", points: 25 },
      { text: "Diponegoro", points: 20 },
      { text: "RA Kartini", points: 15 },
      { text: "Imam Bonjol", points: 10 },
    ],
  },
  {
    question: "Sebutkan nama presiden Indonesia!",
    answers: [
      { text: "Soekarno", points: 30 },
      { text: "Joko Widodo", points: 25 },
      { text: "Soeharto", points: 25 },
      { text: "Susilo Bambang Yudhoyono", points: 20 },
      { text: "Megawati Soekarnoputri", points: 15 },
      { text: "BJ Habibie", points: 10 },
      { text: "Abdurrahman Wahid (Gus Dur)", points: 10 },
      { text: "Prabowo", points: 10 },
    ],
  },
  {
    question: "Sebutkan perusahaan teknologi terbesar di dunia!",
    answers: [
      { text: "Apple", points: 30 },
      { text: "Microsoft", points: 25 },
      { text: "Google", points: 20 },
      { text: "Amazon", points: 15 },
      { text: "Facebook", points: 10 },
    ],
  },
  {
    question: "Sebutkan jenis makanan tradisional Jepang!",
    answers: [
      { text: "Sushi", points: 30 },
      { text: "Ramen", points: 25 },
      { text: "Tempura", points: 20 },
      { text: "Takoyaki", points: 15 },
      { text: "Sashimi", points: 10 },
    ],
  },
  {
    question:
      "Sebutkan nama pesawat luar angkasa yang pertama kali mendarat di bulan!",
    answers: [
      { text: "Apollo 11", points: 30 },
      { text: "Luna 2", points: 25 },
      { text: "Sputnik 1", points: 20 },
      { text: "Voyager 1", points: 15 },
      { text: "Chandrayaan-2", points: 10 },
    ],
  },
  {
    question: "Sebutkan nama film animasi yang dibuat oleh Pixar!",
    answers: [
      { text: "Toy Story", points: 30 },
      { text: "Finding Nemo", points: 25 },
      { text: "Up", points: 20 },
      { text: "Monsters, Inc.", points: 15 },
      { text: "Cars", points: 10 },
    ],
  },
  {
    question: "Apa yang kamu lakukan jika pacar sedang marah?",
    answers: [
      { text: "minta maaf", points: 30 },
      { text: "tanya kenapa", points: 25 },
      { text: "beri hadiah kecil", points: 20 },
      { text: "ajak jalan-jalan", points: 15 },
      { text: "diam saja", points: 10 },
    ],
  },
  {
    question: "Sebutkan bahasa pemrograman yang populer!",
    answers: [
      { text: "Python", points: 30 },
      { text: "JavaScript", points: 25 },
      { text: "Java", points: 20 },
      { text: "C++", points: 15 },
      { text: "Go", points: 10 },
    ],
  },
  {
    question: "Sebutkan planet dalam tata surya selain Bumi!",
    answers: [
      { text: "Mars", points: 25 },
      { text: "Jupiter", points: 25 },
      { text: "Venus", points: 20 },
      { text: "Saturnus", points: 15 },
      { text: "Merkurius", points: 10 },
      { text: "Neptunus", points: 10 },
      { text: "Uranus", points: 10 },
    ],
  },
  {
    question: "Sebutkan makanan yang berasal dari Italia!",
    answers: [
      { text: "Pizza", points: 30 },
      { text: "Pasta", points: 25 },
      { text: "Risotto", points: 20 },
      { text: "Tiramisu", points: 15 },
      { text: "Gelato", points: 10 },
    ],
  },
  {
    question: "Sebutkan jenis-jenis awan yang umum dikenal!",
    answers: [
      { text: "Kumulus", points: 30 },
      { text: "Stratus", points: 25 },
      { text: "Sirus", points: 20 },
      { text: "Nimbus", points: 15 },
      { text: "Altokumulus", points: 10 },
    ],
  },
  {
    question: "Sebutkan alat musik tradisional Indonesia!",
    answers: [
      { text: "Angklung", points: 30 },
      { text: "Gamelan", points: 25 },
      { text: "Sasando", points: 20 },
      { text: "Kolintang", points: 15 },
      { text: "Tifa", points: 10 },
    ],
  },
];

module.exports = questions;
